site_name: Experiment Data Depot
repo_url: https://github.com/jbei/edd
edit_uri: edit/trunk/docs/
nav:
  - Home: index.md
  - "User Guide":
      - Tutorials: Tutorials.md
      - "Frequently Asked Questions": FAQ.md
  - "Admin Guide":
      - Administration: Administration.md
      - Configuration: Configuration.md
      - Deployment: Deployment.md
      - "Migration 2.5 to 2.6": Migration_2.5_to_2.6.md
      - "Migration 2.6 to 2.7": Migration_2.6_to_2.7.md
      - About:
          - License: License.md
          - Legal: Legal.md
          - Contributing: Contributing.md
  - Development:
      - "Developer Setup":
          - "Developer Setup": Developer_Setup.md
          - "macOS Setup": Developer_Setup_Mac.md
          - "Linux Setup": Developer_Setup_Linux.md
          - "Running Development": Developer_Setup_Running.md
      - Contributing: Contributing.md
      - Troubleshooting: Troubleshooting.md
      - Releasing: Releasing.md
      - "Use Cases": Use_Cases.md
      - "User Stories": User_Stories.md
theme: spacelab
markdown_extensions:
  - codehilite:
  - sane_lists:
  - smarty:
  - toc:
      permalink: True
